spring.application.name=ratelimiter
spring.data.redis.host=living-jaybird-124725.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAec1AAIgcDFiYTQyZmJkZGUxYzg0NDhjYTVmYjY1ZWUzN2MwZGQ1Mg
spring.data.redis.ssl.enabled=true

rate.limit.capacity=5
rate.limit.refill-rate=1

server.port=8080
server.address=0.0.0.0